steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_BUILD_ID=${_COMMIT_SHA}'
      - '--build-arg'
      - 'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_POSTHOG_KEY=${_NEXT_PUBLIC_POSTHOG_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_POSTHOG_HOST=${_NEXT_PUBLIC_POSTHOG_HOST}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FINMEMORY_PUBLIC_ACCESS=${_NEXT_PUBLIC_FINMEMORY_PUBLIC_ACCESS}'
      - '--build-arg'
      - 'NEXT_PUBLIC_RETAILER_APP_URL=${_NEXT_PUBLIC_RETAILER_APP_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_CONSUMER_APP_URL=${_NEXT_PUBLIC_CONSUMER_APP_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=${_NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}'
      - '-f'
      - 'Dockerfile.retailer'
      - '-t'
      - 'gcr.io/$PROJECT_ID/finmemorycomerciantes:$_COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/finmemorycomerciantes:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/finmemorycomerciantes:$_COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/finmemorycomerciantes:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'finmemorycomerciantes'
      - '--image'
      - 'gcr.io/$PROJECT_ID/finmemorycomerciantes:$_COMMIT_SHA'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--timeout'
      - '60s'
      - '--max-instances'
      - '10'
      - '--cpu'
      - '1'

images:
  - 'gcr.io/$PROJECT_ID/finmemorycomerciantes:$_COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/finmemorycomerciantes:latest'

substitutions:
  _COMMIT_SHA: 'manual'
  _NEXT_PUBLIC_SUPABASE_URL: ''
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: ''
  _NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ''
  _NEXT_PUBLIC_POSTHOG_KEY: ''
  _NEXT_PUBLIC_POSTHOG_HOST: ''
  _NEXT_PUBLIC_FINMEMORY_PUBLIC_ACCESS: '1'
  _NEXT_PUBLIC_RETAILER_APP_URL: ''
  _NEXT_PUBLIC_CONSUMER_APP_URL: 'https://finmemory.com.br'
  _NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ''
